document: system-outline
group: 32NF
state: WD
type: ST
number: 2120
part: 1
project: TLX
title: Systems
#note: DRAFT
format: docx
refdoc: "AG04-1-2016-SMPTE-ST-RP-Template-2016-08-29(pandoc).dotx"
templates: "{HOME}/OneDrive/Documents/SMPTE/Templates"
